-- RETAIL SNOWFLAKE DATA WAREHOUSE
-- 01 - Environment Setup

CREATE OR REPLACE DATABASE RETAIL_DWH;

CREATE OR REPLACE WAREHOUSE RETAIL_DEV_WH
WITH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

CREATE OR REPLACE SCHEMA RETAIL_DWH.RAW;
CREATE OR REPLACE SCHEMA RETAIL_DWH.STAGING;
CREATE OR REPLACE SCHEMA RETAIL_DWH.CORE;
CREATE OR REPLACE SCHEMA RETAIL_DWH.DATA_MART;
CREATE OR REPLACE SCHEMA RETAIL_DWH.DATA_QUALITY;
