-- CUSTOMERS
CREATE OR REPLACE TABLE RAW_CUSTOMERS (
  CUSTOMER_ID NUMBER, 
  FIRST_NAME VARCHAR,
  LAST_NAME VARCHAR, 
  EMAIL VARCHAR,
  PHONE VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  COUNTRY VARCHAR,
  CUSTOMER_TYPE VARCHAR,
  CREATED_DATE TIMESTAMP,
  UPDATED_DATE TIMESTAMP
)
--Load
COPY INTO RAW_CUSTOMERS
FROM @RETAIL.RAW_STAGE/customers.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RETAIL_DWH.RAW.CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';
--validate
SELECT COUNT(*) AS CUSTOMER_COUNT
FROM RAW_CUSTOMERS;

--PRODUCTS
CREATE TABLE RAW_PRODUCTS (
  PRODUCT_ID NUMBER, 
  PRODUCT _NAME VARCHAR,
  CATEGORY VARCHAR,
  SUBCATEGORY VARCHAR,
  BRAND VARCHAR,
  PRICE NUMBER,
  COST NUMBER,
  SUPPLIER_ID NUMBER,
  STOCK_QUANTITY NUMBER,
  CREATED_DATE TIMESTAMP,
  UPDATED_DATE TIMESTAMP
)
-- load
COPY INTO RAW_PRODUCTS
FROM @RETAIL.RAW.RAW_STAGE/products.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RETAIL_DWH.RAW.CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';
--validate
SELECT COUNT(*) AS PRODUCT_COUNT
FROM RAW_PRODUCTS;

--STORES
CREATE TABLE RAW_STORES (
  STORE_ID NUMBER, 
  STORE_NAME VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  COUNTRY VARCHAR,
  REGION VARCHAR,
  MANAGER VARCHAR,
  OPENED_DATE DATE
  )
--load
COPY INTO RAW_STORES
FROM @RETAIL.RAW.RAW_STAGE/stores.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RETAIL_DWH.RAW.CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';
--validate
SELECT COUNT(*) AS STORE_COUNT
FROM RAW_STORES;

-- ORDERS
CREATE TABLE RAW_ORDERS (
  ORDER_ID NUMBER,
  CUSTOMER_ID NUMBER,
  STORE_ID NUMBER,
  ORDER _DATE DATE,
  ORDER_STATUS VARCHAR,
  PAYMENT_STATUS VARCHAR,
  TOTAL_AMOUNT NUMBER,
  UPDATED_DATE TIMESTAMP
)
-- load
COPY INTO RAW_ORDERS
FROM @RETAIL_RAW_STAGE/orders.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RETAIL_DWH.RAW.CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';
--validate
SELECT COUNT(*) AS ORDER_COUNT
FROM RAW_ORDERS;

--ORDER ITEMS
CREATE TABLE RAW_ORDER_ITEMS (
  ORDER_ITEM_ID NUMBER,
  ORDER_ID NUMBER,
  PRODUCT_ID NUMBER,
  QUANTITY NUMBER,
  UNIT_PRICE NUMBER,
  DISCOUNT NUMBER
)
-- load
COPY INTO RAW_ORDER_ITEMS
FROM @RETAIL_RAW_STAGE/order_items.csv
FILE_FORMAT = (
    FORMAT_NAME = 'RETAIL_DWH.RAW.CSV_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';
-- validate
SELECT COUNT(*) AS ORDER_ITEM_COUNT
FROM RAW_ORDER_ITEMS;
  
-- CUSTOMER EVENTS
CREATE TABLE RAW CUSTOMER_ EVENTS (
  EVENT_DATA VARIANT
  )
-- load
COPY INTO RAW_CUSTOMER_EVENTS
FROM @RETAIL_RAW_STAGE/customer_events.json
FILE_FORMAT = (
    FORMAT_NAME = 'RETAIL_DWH.RAW.JSON_FORMAT'
)
ON_ERROR = 'ABORT_STATEMENT';
--validate
SELECT COUNT(*) AS CUSTOMER_EVENT_COUNT
FROM RAW_CUSTOMER_EVENTS;
