-- CUSTOMER --
CREATE OR REPLACE TABLE RETAIL_DWH.STG.STG_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    TRIM(FIRST_NAME) AS FIRST_NAME,
    TRIM(LAST_NAME) AS LAST_NAME,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    TRIM(PHONE) AS PHONE,
    TRIM(CITY) AS CITY,
    TRIM(STATE) AS STATE,
    TRIM(COUNTRY) AS COUNTRY,
    TRIM(CUSTOMER_TYPE) AS CUSTOMER_TYPE,
    CREATED_DATE,
    UPDATED_DATE
FROM RETAIL_DWH.RAW.RAW_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

-- PRODUCTS --
CREATE OR REPLACE TABLE RETAIL_DWH.STAGING.STG_PRODUCTS AS
SELECT
    PRODUCT_ID,
    TRIM(PRODUCT_NAME) AS PRODUCT_NAME,
    INITCAP(TRIM(CATEGORY)) AS CATEGORY,
    TRIM(SUBCATEGORY) AS SUBCATEGORY,
    TRIM(BRAND) AS BRAND,
    PRICE,
    COST,
    SUPPLIER_ID,
    STOCK_QUANTITY,
    CREATED_DATE,
    UPDATED_DATE
FROM RETAIL_DWH.RAW.RAW_PRODUCTS
WHERE PRODUCT_ID IS NOT NULL;

-- ORDER ITEMS --
CREATE OR REPLACE TABLE RETAIL_DWH.STAGING.STG_ORDER_ITEMS AS
SELECT
    ORDER_ITEM_ID,
    ORDER_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    DISCOUNT,
    ROUND(
        (QUANTITY * UNIT_PRICE) - DISCOUNT,
    2
    ) AS LINE_AMOUNT
FROM RETAIL_DWH.RAW.RAW_ORDER_ITEMS
WHERE ORDER_ITEM_ID IS NOT NULL;

-- ORDERS --
CREATE OR REPLACE TABLE RETAIL_DWH.STAGING.STG_ORDERS AS
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    STORE_ID,
    ORDER_DATE,
    UPPER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,
    UPPER(TRIM(PAYMENT_STATUS)) AS PAYMENT_STATUS,
    TOTAL_AMOUNT,
    UPDATED_DATE
FROM RETAIL_DWH.RAW.RAW_ORDERS
WHERE ORDER_ID IS NOT NULL;

-- STORES --
CREATE OR REPLACE TABLE RETAIL_DWH.STAGING.STG_STORES AS
SELECT
    STORE_ID,
    TRIM(STORE_NAME) AS STORE_NAME,
    INITCAP(TRIM(CITY)) AS CITY,
    INITCAP(TRIM(STATE)) AS STATE,
    INITCAP(TRIM(COUNTRY)) AS COUNTRY,
    INITCAP(TRIM(REGION)) AS REGION,
    TRIM(MANAGER) AS MANAGER,
    OPENED_DATE
FROM RETAIL_DWH.RAW.RAW_STORES
WHERE STORE_ID IS NOT NULL;

-- CUSTOMER EVENTS --
CREATE OR REPLACE TABLE RETAIL_DWH.STAGING.STG_CUSTOMER_EVENTS AS
SELECT
    EVENT_DATA:customer_id::NUMBER AS CUSTOMER_ID,
    EVENT_DATA:event_id::VARCHAR AS EVENT_ID,
    TO_TIMESTAMP_NTZ(
        EVENT_DATA:event_timestamp::VARCHAR
    ) AS EVENT_TIMESTAMP,
    UPPER(
        TRIM(EVENT_DATA:event_type::VARCHAR)
    ) AS EVENT_TYPE,
    EVENT_DATA:device:os::VARCHAR AS DEVICE_OS,
    EVENT_DATA:device:type::VARCHAR AS DEVICE_TYPE,
    EVENT_DATA:product AS PRODUCT_DATA
FROM RETAIL_DWH.RAW.RAW_CUSTOMER_EVENTS
WHERE EVENT_DATA:event_id IS NOT NULL;

-- EVENT PRODUCTS --
CREATE OR REPLACE TABLE RETAIL_DWH.STAGING.STG_EVENT_PRODUCTS AS
SELECT
    EVENT_ID,
    CUSTOMER_ID,
    EVENT_TIMESTAMP,
    EVENT_TYPE,
    PRODUCT_DATA:product_id::NUMBER AS PRODUCT_ID,
    INITCAP(
        TRIM(PRODUCT_DATA:category::VARCHAR)
    ) AS PRODUCT_CATEGORY,
    DEVICE_OS,
    DEVICE_TYPE
FROM RETAIL_DWH.STAGING.STG_CUSTOMER_EVENTS
WHERE PRODUCT_DATA IS NOT NULL
  AND PRODUCT_DATA:product_id IS NOT NULL;

-- VALIDATE STAGING TABLES
SELECT COUNT(*) AS CUSTOMER_COUNT
FROM RETAIL_DWH.STAGING.STG_CUSTOMERS;

SELECT COUNT(*) AS PRODUCT_COUNT
FROM RETAIL_DWH.STAGING.STG_PRODUCTS;

SELECT COUNT(*) AS STORE_COUNT
FROM RETAIL_DWH.STAGING.STG_STORES;

SELECT COUNT(*) AS ORDER_COUNT
FROM RETAIL_DWH.STAGING.STG_ORDERS;

SELECT COUNT(*) AS ORDER_ITEM_COUNT
FROM RETAIL_DWH.STAGING.STG_ORDER_ITEMS;

SELECT COUNT(*) AS CUSTOMER_EVENT_COUNT
FROM RETAIL_DWH.STAGING.STG_CUSTOMER_EVENTS;
