-- DIM CUSTOMER
CREATE OR REPLACE TABLE RETAIL_DWH.CORE.DIM_CUSTOMER AS

SELECT
    ROW_NUMBER() OVER (ORDER BY CUSTOMER_ID) AS CUSTOMER_KEY,
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    TRIM(FIRST_NAME || ' ' || LAST_NAME) AS CUSTOMER_NAME,
    EMAIL,
    PHONE,
    CITY,
    STATE,
    COUNTRY,
    CUSTOMER_TYPE,
    CREATED_DATE,
    UPDATED_DATE

FROM RETAIL_DWH.STAGING.STG_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

-- DIM PRODUCT
CREATE OR REPLACE TABLE RETAIL_DWH.CORE.DIM_PRODUCT AS

SELECT
    ROW_NUMBER() OVER (ORDER BY PRODUCT_ID) AS PRODUCT_KEY,
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUBCATEGORY,
    BRAND,
    PRICE,
    COST,
    SUPPLIER_ID,
    STOCK_QUANTITY,
    CREATED_DATE,
    UPDATED_DATE

FROM RETAIL_DWH.STAGING.STG_PRODUCTS
WHERE PRODUCT_ID IS NOT NULL;

-- DIM DATE
CREATE OR REPLACE TABLE RETAIL_DWH.CORE.DIM_DATE AS

WITH DATE_RANGE AS (
    SELECT
        MIN(ORDER_DATE::DATE) AS START_DATE,
        MAX(ORDER_DATE::DATE) AS END_DATE
    FROM RETAIL_DWH.STAGING.STG_ORDERS
),

DATE_SERIES AS (
    SELECT
        DATEADD(DAY, SEQ4(), START_DATE)::DATE AS DATE_VALUE
    FROM DATE_RANGE,
         TABLE(GENERATOR(ROWCOUNT => 5000))
    WHERE DATEADD(DAY, SEQ4(), START_DATE)::DATE <= END_DATE
)

SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')) AS DATE_KEY,
    DATE_VALUE AS FULL_DATE,
    YEAR(DATE_VALUE) AS YEAR,
    QUARTER(DATE_VALUE) AS QUARTER,
    MONTH(DATE_VALUE) AS MONTH,
    MONTHNAME(DATE_VALUE) AS MONTH_NAME,
    WEEK(DATE_VALUE) AS WEEK_OF_YEAR,
    DAYOFMONTH(DATE_VALUE) AS DAY_OF_MONTH,
    DAYOFWEEK(DATE_VALUE) AS DAY_OF_WEEK,
    DAYNAME(DATE_VALUE) AS DAY_NAME

FROM DATE_SERIES;

-- DIM STORE
CREATE OR REPLACE TABLE RETAIL_DWH.CORE.DIM_STORE AS

SELECT
    ROW_NUMBER() OVER (ORDER BY STORE_ID) AS STORE_KEY,
    STORE_ID,
    STORE_NAME,
    CITY,
    STATE,
    COUNTRY,
    REGION,
    MANAGER,
    OPENED_DATE

FROM RETAIL_DWH.STAGING.STG_STORES
WHERE STORE_ID IS NOT NULL;
