-- FACT ORDER
CREATE OR REPLACE TABLE RETAIL_DWH.CORE.FACT_ORDER AS

SELECT
    O.ORDER_ID,
    C.CUSTOMER_KEY,
    S.STORE_KEY,
    D.DATE_KEY,
    O.ORDER_DATE,
    O.ORDER_STATUS,
    O.PAYMENT_STATUS,
    O.TOTAL_AMOUNT,
    O.UPDATED_DATE

FROM RETAIL_DWH.STAGING.STG_ORDERS O
LEFT JOIN RETAIL_DWH.CORE.DIM_CUSTOMER C
    ON O.CUSTOMER_ID = C.CUSTOMER_ID
LEFT JOIN RETAIL_DWH.CORE.DIM_STORE S
    ON O.STORE_ID = S.STORE_ID
LEFT JOIN RETAIL_DWH.CORE.DIM_DATE D
    ON O.ORDER_DATE::DATE = D.FULL_DATE
WHERE O.ORDER_ID IS NOT NULL;

-- FACT ORDER ITEM
CREATE OR REPLACE TABLE RETAIL_DWH.CORE.FACT_ORDER_ITEM AS

SELECT
    oi.ORDER_ITEM_ID,
    oi.ORDER_ID,
    p.PRODUCT_KEY,
    oi.QUANTITY,
    oi.UNIT_PRICE,
    oi.DISCOUNT,
    oi.LINE_AMOUNT

FROM RETAIL_DWH.STAGING.STG_ORDER_ITEMS oi
LEFT JOIN RETAIL_DWH.CORE.DIM_PRODUCT p
    ON oi.PRODUCT_ID = p.PRODUCT_ID
WHERE oi.ORDER_ITEM_ID IS NOT NULL;

-- FACT CUSTOMER EVENT
CREATE OR REPLACE TABLE RETAIL_DWH.CORE.FACT_CUSTOMER_EVENT AS
SELECT
    e.EVENT_ID,
    c.CUSTOMER_KEY,
    p.PRODUCT_KEY,
    e.EVENT_TIMESTAMP,
    e.EVENT_TYPE,
    e.DEVICE_OS,
    e.DEVICE_TYPE,
    ep.PRODUCT_CATEGORY
FROM RETAIL_DWH.STAGING.STG_CUSTOMER_EVENTS e
LEFT JOIN RETAIL_DWH.CORE.DIM_CUSTOMER c
    ON e.CUSTOMER_ID = c.CUSTOMER_ID
LEFT JOIN RETAIL_DWH.STAGING.ST_EVENT_PRODUCTS ep
    ON e.EVENT_ID = ep.EVENT_ID
LEFT JOIN RETAIL_DWH.CORE.DIM_PRODUCT p
    ON ep.PRODUCT_ID = p.PRODUCT_ID
WHERE e.EVENT_ID IS NOT NULL;

-- VALIDATION
SELECT COUNT(*) AS CUSTOMER_EVENT_COUNT
FROM RETAIL_DWH.CORE.FACT_CUSTOMER_EVENTS;

SELECT COUNT(*) AS ORDER_COUNT
FROM RETAIL_DWH.CORE.FACT_ORDER;

SELECT COUNT(*) AS ORDER_ITEM_COUNT
FROM RETAIL_DWH.CORE.FACT_ORDER_ITEM;
