-- 1. DAILY SALES
CREATE OR REPLACE TABLE RETAIL_DWH.MART.DM_DAILY_SALES AS
SELECT
    d.FULL_DATE,
    d.YEAR,
    d.QUARTER,
    d.MONTH,
    d.MONTH_NAME,
    d.WEEK_OF_YEAR,

    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT o.CUSTOMER_KEY) AS UNIQUE_CUSTOMERS,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_SALES,
    AVG(o.TOTAL_AMOUNT) AS AVG_ORDER_VALUE

FROM RETAIL_DWH.CORE.FACT_ORDER o
JOIN RETAIL_DWH.CORE.DIM_DATE d
    ON o.DATE_KEY = d.DATE_KEY

GROUP BY
    d.FULL_DATE,
    d.YEAR,
    d.QUARTER,
    d.MONTH,
    d.MONTH_NAME,
    d.WEEK_OF_YEAR;
-- VALIDATE
SELECT * FROM DM_DAILY_SALES
ORDER BY FULL_DATE

-- 2. PRODUCT SALES
CREATE OR REPLACE TABLE RETAIL_DWH.MART.DM_PRODUCT_SALES AS
SELECT
    p.PRODUCT_KEY,
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.SUBCATEGORY,
    p.BRAND,

    COUNT(DISTINCT oi.ORDER_ID) AS TOTAL_ORDERS,
    SUM(oi.QUANTITY) AS TOTAL_QUANTITY,
    SUM(oi.LINE_AMOUNT) AS TOTAL_SALES,
    AVG(oi.UNIT_PRICE) AS AVG_UNIT_PRICE

FROM RETAIL_DWH.CORE.FACT_ORDER_ITEM oi
JOIN RETAIL_DWH.CORE.DIM_PRODUCT p
    ON oi.PRODUCT_KEY = p.PRODUCT_KEY

GROUP BY
    p.PRODUCT_KEY,
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.SUBCATEGORY,
    p.BRAND;

-- VALIDATE
SELECT * FROM DM_PRODUCT_SALES
ORDER BY TOTAL_SALES DESC
LIMIT 10;

-- 3. CUSTOMER SALES
CREATE OR REPLACE TABLE RETAIL_DWH.MART.DM_CUSTOMER_SALES AS
SELECT
    c.CUSTOMER_KEY,
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.EMAIL,
    c.CITY,
    c.STATE,
    c.COUNTRY,
    c.CUSTOMER_TYPE,

    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_SPEND,
    AVG(o.TOTAL_AMOUNT) AS AVG_ORDER_VALUE,
    MIN(o.ORDER_DATE) AS FIRST_ORDER_DATE,
    MAX(o.ORDER_DATE) AS LAST_ORDER_DATE

FROM RETAIL_DWH.CORE.DIM_CUSTOMER c
LEFT JOIN RETAIL_DWH.CORE.FACT_ORDER o
    ON c.CUSTOMER_KEY = o.CUSTOMER_KEY

GROUP BY
    c.CUSTOMER_KEY,
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.EMAIL,
    c.CITY,
    c.STATE,
    c.COUNTRY,
    c.CUSTOMER_TYPE;

-- VALIDATE
SELECT * FROM DM_CUSTOMER_SALES
LIMIT 10;

-- 4. CUSTOMER BEHAVIOR
CREATE OR REPLACE TABLE RETAIL_DWH.MART.DM_CUSTOMER_BEHAVIOR AS
SELECT
    c.CUSTOMER_KEY,
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,

    COUNT(e.EVENT_ID) AS TOTAL_EVENTS,

    COUNT_IF(e.EVENT_TYPE = 'view') AS PRODUCT_VIEWS,

    COUNT_IF(e.EVENT_TYPE = 'add_to_cart') AS ADD_TO_CART_EVENTS,

    COUNT_IF(e.EVENT_TYPE = 'purchase') AS PURCHASE_EVENTS,

    COUNT_IF(e.EVENT_TYPE = 'login') AS LOGIN_EVENTS,

    COUNT_IF(e.EVENT_TYPE = 'logout') AS LOGOUT_EVENTS,

    COUNT(
        DISTINCT CASE
            WHEN e.EVENT_TYPE = 'view'
            THEN e.PRODUCT_KEY
        END
    ) AS UNIQUE_PRODUCTS_VIEWED

FROM RETAIL_DWH.CORE.DIM_CUSTOMER c
LEFT JOIN RETAIL_DWH.CORE.FACT_CUSTOMER_EVENT e
    ON c.CUSTOMER_KEY = e.CUSTOMER_KEY

GROUP BY
    c.CUSTOMER_KEY,
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME;

-- VALIDATE
SELECT * FROM DM_CUSTOMER_BEHAVIOR
LIMIT 10;


LIMIT 10;
