--Monthly Sales
SELECT
    YEAR,
    MONTH,
    MONTH_NAME,
    SUM(TOTAL_SALES) AS TOTAL_SALES,
    SUM(TOTAL_ORDERS) AS TOTAL_ORDERS
FROM RETAIL_DWH.DATA_MART.DM_DAILY_SALES
GROUP BY
    YEAR,
    MONTH,
    MONTH_NAME
ORDER BY YEAR, MONTH;

--Top Products
SELECT
    PRODUCT_NAME,
    CATEGORY,
    BRAND,
    TOTAL_QUANTITY,
    TOTAL_SALES
FROM RETAIL_DWH.DATA_MART.DM_PRODUCT_SALES
ORDER BY TOTAL_SALES DESC
LIMIT 10;

--Top 3 products by category
SELECT
    PRODUCT_NAME,
    CATEGORY,
    TOTAL_SALES,
    RANK() OVER (
        PARTITION BY CATEGORY
        ORDER BY TOTAL_SALES DESC
    ) AS CATEGORY_RANK
FROM RETAIL_DWH.DATA_MART.DM_PRODUCT_SALES
QUALIFY CATEGORY_RANK <= 3
ORDER BY CATEGORY, CATEGORY_RANK;

--Month over month growth
WITH monthly_sales AS (
    SELECT
        YEAR,
        MONTH,
        MONTH_NAME,
        SUM(TOTAL_SALES) AS TOTAL_SALES
    FROM RETAIL_DWH.DATA_MART.DM_DAILY_SALES
    GROUP BY
        YEAR,
        MONTH,
        MONTH_NAME
),

sales_with_previous AS (
    SELECT
        YEAR,
        MONTH,
        MONTH_NAME,
        TOTAL_SALES,
        LAG(TOTAL_SALES) OVER (
            ORDER BY YEAR, MONTH
        ) AS PREVIOUS_MONTH_SALES
    FROM monthly_sales
)

SELECT
    YEAR,
    MONTH,
    MONTH_NAME,
    TOTAL_SALES,
    PREVIOUS_MONTH_SALES,
    ROUND(
        ((TOTAL_SALES - PREVIOUS_MONTH_SALES)
        / NULLIF(PREVIOUS_MONTH_SALES, 0)) * 100,
        2
    ) AS MOM_GROWTH_PERCENT
FROM sales_with_previous
ORDER BY YEAR, MONTH;
--Top customers
SELECT
    CUSTOMER_NAME,
    CUSTOMER_TYPE,
    TOTAL_ORDERS,
    TOTAL_SPEND,
    AVG_ORDER_VALUE
FROM RETAIL_DWH.DATA_MART.DM_CUSTOMER_SALES
ORDER BY TOTAL_SPEND DESC
LIMIT 20;

--Store performance
SELECT
    s.STORE_NAME,
    s.CITY,
    s.REGION,
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_SALES,
    AVG(o.TOTAL_AMOUNT) AS AVG_ORDER_VALUE
FROM RETAIL_DWH.CORE.FACT_ORDER o
JOIN RETAIL_DWH.CORE.DIM_STORE s
    ON o.STORE_KEY = s.STORE_KEY
GROUP BY
    s.STORE_NAME,
    s.CITY,
    s.REGION
ORDER BY TOTAL_SALES DESC;

--Customer event distribution
SELECT
    EVENT_TYPE,
    COUNT(*) AS EVENT_COUNT
FROM RETAIL_DWH.CORE.FACT_CUSTOMER_EVENT
GROUP BY EVENT_TYPE
ORDER BY EVENT_COUNT DESC;

--Device behaviour
SELECT
    EVENT_TYPE,
    COUNT(*) AS EVENT_COUNT
FROM RETAIL_DWH.CORE.FACT_CUSTOMER_EVENT
GROUP BY EVENT_TYPE
ORDER BY EVENT_COUNT DESC;
