--Create
CREATE OR REPLACE SCHEMA RETAIL_DWH.DATA_QUALITY;

--Audit table
CREATE OR REPLACE TABLE RETAIL_DWH.DATA_QUALITY.DQ_RESULTS (
    CHECK_TIME TIMESTAMP,
    TABLE_NAME VARCHAR,
    CHECK_NAME VARCHAR,
    RECORD_COUNT NUMBER,
    FAILED_RECORDS NUMBER,
    STATUS VARCHAR
);

--Customer null check
INSERT INTO RETAIL_DWH.DATA_QUALITY.DQ_RESULTS
SELECT
    CURRENT_TIMESTAMP(),
    'DIM_CUSTOMER',
    'NULL_CUSTOMER_ID',
    COUNT(*),
    COUNT_IF(CUSTOMER_ID IS NULL),
    IFF(COUNT_IF(CUSTOMER_ID IS NULL) = 0, 'PASS', 'FAIL')
FROM RETAIL_DWH.CORE.DIM_CUSTOMER;

--Product null check
INSERT INTO RETAIL_DWH.DATA_QUALITY.DQ_RESULTS
SELECT
    CURRENT_TIMESTAMP(),
    'DIM_PRODUCT',
    'NULL_PRODUCT_ID',
    COUNT(*),
    COUNT_IF(PRODUCT_ID IS NULL),
    IFF(COUNT_IF(PRODUCT_ID IS NULL) = 0, 'PASS', 'FAIL')
FROM RETAIL_DWH.CORE.DIM_PRODUCT;

--Order duplicate check
INSERT INTO RETAIL_DWH.DATA_QUALITY.DQ_RESULTS
SELECT
    CURRENT_TIMESTAMP(),
    'FACT_ORDER',
    'DUPLICATE_ORDER_ID',
    COUNT(*),
    COUNT(*) - COUNT(DISTINCT ORDER_ID),
    IFF(
        COUNT(*) = COUNT(DISTINCT ORDER_ID),
        'PASS',
        'FAIL'
    )
FROM RETAIL_DWH.CORE.FACT_ORDER;

--validate
SELECT *
FROM RETAIL_DWH.DATA_QUALITY.DQ_RESULTS
ORDER BY CHECK_TIME DESC;
