-- Snowflake Stream
-- Tracks changes to STG_ORDERS

CREATE OR REPLACE STREAM RETAIL_DWH.STAGING.STG_ORDERS_STREAM
ON TABLE RETAIL_DWH.STAGING.STG_ORDERS;

-- View stream metadata
SELECT *
FROM RETAIL_DWH.STAGING.STG_ORDERS_STREAM;

-- Demonstrate change tracking
UPDATE RETAIL_DWH.STAGING.STG_ORDERS
SET ORDER_STATUS = 'STREAM_TEST'
WHERE ORDER_ID = 1000001;

-- View captured change
SELECT *
FROM RETAIL_DWH.STAGING.STG_ORDERS_STREAM;

--Revert test Data
Update RETAIL_DWH.STAGING.STG_ORDERS
SET ORDER_STATUS = 'CANCELLED'
WHERE ORDER_ID = '1000001'
