--Create
CREATE OR REPLACE TASK RETAIL_DWH.DATA_MART.TASK_REFRESH_DAILY_SALES
WAREHOUSE = RETAIL_DEV_WH
SCHEDULE = 'USING CRON 0 * * * * UTC'
AS
CREATE OR REPLACE TABLE RETAIL_DWH.DATA_MART.DM_DAILY_SALES AS
SELECT
    d.FULL_DATE,
    d.YEAR,
    d.QUARTER,
    d.MONTH,
    d.MONTH_NAME,
    d.WEEK_OF_YEAR,
    COUNT(DISTINCT o.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT o.CUSTOMER_KEY) AS UNIQUE_CUSTOMERS,
    SUM(o.TOTAL_AMOUNT) AS TOTAL_SALES,
    AVG(o.TOTAL_AMOUNT) AS AVG_ORDER_VALUE
FROM RETAIL_DWH.CORE.FACT_ORDER o
JOIN RETAIL_DWH.CORE.DIM_DATE d
    ON o.DATE_KEY = d.DATE_KEY
GROUP BY
    d.FULL_DATE,
    d.YEAR,
    d.QUARTER,
    d.MONTH,
    d.MONTH_NAME
    d.WEEK_OF_YEAR

--Validate
SHOW TASKS IN SCHEMA RETAIL_DWH.DATA_MART; 

  
    d.MONTH_NAME,
    d.WEEK_OF_YEAR;
