-- 10_TASKS.SQL
-- Automated CDC Processing Using Snowflake Task
-- Downstream table used for CDC demonstration

CREATE OR REPLACE TABLE RETAIL_DWH.DATA_MART.CDC_ORDER_DEMO (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    STORE_ID NUMBER,
    ORDER_DATE DATE,
    ORDER_STATUS VARCHAR,
    PAYMENT_STATUS VARCHAR,
    TOTAL_AMOUNT NUMBER(12,2),
    UPDATED_DATE TIMESTAMP,
    CDC_ACTION VARCHAR,
    CDC_PROCESSED_AT TIMESTAMP
);

-- Create Task to process Stream changes
CREATE OR REPLACE TASK RETAIL_DWH.DATA_MART.TASK_PROCESS_ORDER_CDC
WAREHOUSE = RETAIL_DEV_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA(
    'RETAIL_DWH.STAGING.STG_ORDERS_STREAM'
)
AS
INSERT INTO RETAIL_DWH.DATA_MART.CDC_ORDER_DEMO
SELECT
    ORDER_ID,
    CUSTOMER_ID,
    STORE_ID,
    ORDER_DATE::DATE,
    ORDER_STATUS,
    PAYMENT_STATUS,
    TOTAL_AMOUNT,
    UPDATED_DATE,
    METADATA$ACTION,
    CURRENT_TIMESTAMP()
FROM RETAIL_DWH.STAGING.STG_ORDERS_STREAM;

-- Check Task
SHOW TASKS IN SCHEMA RETAIL_DWH.DATA_MART;

-- Resume Task for demonstration
ALTER TASK RETAIL_DWH.DATA_MART.TASK_PROCESS_ORDER_CDC RESUME;

-- Check Task execution history
SELECT *
FROM TABLE(
    RETAIL_DWH.INFORMATION_SCHEMA.TASK_HISTORY(
        TASK_NAME => 'TASK_PROCESS_ORDER_CDC',
        RESULT_LIMIT => 20
    )
)
ORDER BY SCHEDULED_TIME DESC;

-- View processed CDC records
SELECT *
FROM RETAIL_DWH.DATA_MART.CDC_ORDER_DEMO
ORDER BY CDC_PROCESSED_AT DESC;

-- IMPORTANT:
-- Suspend the Task after testing to avoid unnecessary execution.

ALTER TASK RETAIL_DWH.DATA_MART.TASK_PROCESS_ORDER_CDC SUSPEND;
