-- Query History / Performance Monitoring
SELECT
    QUERY_ID,
    QUERY_TEXT,
    EXECUTION_TIME,
    BYTES_SCANNED,
    ROWS_PRODUCED
FROM TABLE(
    RETAIL_DWH.INFORMATION_SCHEMA.QUERY_HISTORY(
        RESULT_LIMIT => 100
    )
)
WHERE QUERY_TEXT ILIKE '%FACT_ORDER%'
ORDER BY START_TIME DESC
LIMIT 20;
