-- Slowly Changing Dimension Type 2 Demonstration
-- Create SCD Type 2 customer dimension
CREATE OR REPLACE TABLE RETAIL_DWH.CORE.DIM_CUSTOMER_SCD2 (
    CUSTOMER_KEY NUMBER,
    CUSTOMER_ID NUMBER,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    CUSTOMER_NAME VARCHAR,
    EMAIL VARCHAR,
    PHONE VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    CUSTOMER_TYPE VARCHAR,
    CREATED_DATE DATE,
    UPDATED_DATE TIMESTAMP,
    EFFECTIVE_FROM TIMESTAMP,
    EFFECTIVE_TO TIMESTAMP,
    IS_CURRENT BOOLEAN
);


-- Initial load
INSERT INTO RETAIL_DWH.CORE.DIM_CUSTOMER_SCD2
SELECT
    ROW_NUMBER() OVER (ORDER BY CUSTOMER_ID) AS CUSTOMER_KEY,
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    FIRST_NAME || ' ' || LAST_NAME AS CUSTOMER_NAME,
    EMAIL,
    PHONE,
    CITY,
    STATE,
    COUNTRY,
    CUSTOMER_TYPE,
    CREATED_DATE,
    UPDATED_DATE,

    COALESCE(UPDATED_DATE, CURRENT_TIMESTAMP()) AS EFFECTIVE_FROM,
    '9999-12-31 23:59:59'::TIMESTAMP AS EFFECTIVE_TO,

    TRUE AS IS_CURRENT

FROM RETAIL_DWH.STAGING.STG_CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

-- Detect changed customer attributes
SELECT
    s.CUSTOMER_ID,
    s.CITY AS NEW_CITY,
    d.CITY AS OLD_CITY,
    s.STATE AS NEW_STATE,
    d.STATE AS OLD_STATE
FROM RETAIL_DWH.STAGING.STG_CUSTOMERS s
JOIN RETAIL_DWH.CORE.DIM_CUSTOMER_SCD2 d
    ON s.CUSTOMER_ID = d.CUSTOMER_ID
WHERE d.IS_CURRENT = TRUE
  AND (
        NVL(s.CITY, '') <> NVL(d.CITY, '')
        OR NVL(s.STATE, '') <> NVL(d.STATE, '')
      );

-- Expire the existing version
UPDATE RETAIL_DWH.CORE.DIM_CUSTOMER_SCD2 d
SET
    EFFECTIVE_TO = CURRENT_TIMESTAMP(),
    IS_CURRENT = FALSE
FROM RETAIL_DWH.STAGING.STG_CUSTOMERS s
WHERE d.CUSTOMER_ID = s.CUSTOMER_ID
  AND d.IS_CURRENT = TRUE
  AND (
        NVL(s.CITY, '') <> NVL(d.CITY, '')
        OR NVL(s.STATE, '') <> NVL(d.STATE, '')
      );


-- Insert the new customer version
INSERT INTO RETAIL_DWH.CORE.DIM_CUSTOMER_SCD2
SELECT
    COALESCE(
        (SELECT MAX(CUSTOMER_KEY)
         FROM RETAIL_DWH.CORE.DIM_CUSTOMER_SCD2),
        0
    )
    + ROW_NUMBER() OVER (ORDER BY s.CUSTOMER_ID) AS CUSTOMER_KEY,

    s.CUSTOMER_ID,
    s.FIRST_NAME,
    s.LAST_NAME,
    s.FIRST_NAME || ' ' || s.LAST_NAME AS CUSTOMER_NAME,
    s.EMAIL,
    s.PHONE,
    s.CITY,
    s.STATE,
    s.COUNTRY,
    s.CUSTOMER_TYPE,
    s.CREATED_DATE,
    s.UPDATED_DATE,

    CURRENT_TIMESTAMP() AS EFFECTIVE_FROM,
    '9999-12-31 23:59:59'::TIMESTAMP AS EFFECTIVE_TO,

    TRUE AS IS_CURRENT

FROM RETAIL_DWH.STAGING.STG_CUSTOMERS s
WHERE s.CUSTOMER_ID = 1001;


-- Verify historical versions
SELECT
    CUSTOMER_KEY,
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CITY,
    STATE,
    EFFECTIVE_FROM,
    EFFECTIVE_TO,
    IS_CURRENT
FROM RETAIL_DWH.CORE.DIM_CUSTOMER_SCD2
WHERE CUSTOMER_ID = 1001
ORDER BY EFFECTIVE_FROM;
